version: '3.8'
services:
  myapp:
    image: mylaw_local
    ports:
      - "8501:8501"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models/llama3-3b:/app/models/llama3-3b
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
